/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 legend.glb 
Author: ahsjkdhsjkah (https://sketchfab.com/ahsjkdhsjkah)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hero-layla-lobby-22d990d782a643ae94b65edb08670e5d
Title: Hero_layla_Lobby
*/

import React from 'react'
import { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import * as THREE from 'three'


export default function Legend({props,command}) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('./models/legend.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions, names } = useAnimations(animations, group)
  
  useEffect(() => {
    if (command && actions && names.length > 0) {
      const firstAction = actions[names[0]].reset().fadeIn(0.5).play()
      firstAction.clampWhenFinished = true
      firstAction.loop = THREE.LoopOnce
      const timeoutId = setTimeout(() => {
        firstAction.stop()
        if (names[1]) {
          const secondAction = actions[names[1]].reset().fadeIn(0).play()
        }
      }, 7633)
      return () => clearTimeout(timeoutId)
    }
  }, [actions, names,command])


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={102.077}>
          <group name="hero_war2shooter_skin_high_addfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="hero_war2shooter_skin_high_add">
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_7" />
                    <group name="Object_9" position={[0, 0, 0.005]} rotation={[-Math.PI / 2, 0, 0]} />
                    <group name="Hero_Directional_light" rotation={[2.772, -0.327, 3.095]} scale={0.923} />
                    <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.war2mat_shooter_skin01_high2} skeleton={nodes.Object_8.skeleton} />
                    <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.war2mat_shooter_skin01_high} skeleton={nodes.Object_10.skeleton} />
                    <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.war2mat_shooter_skin01_high1} skeleton={nodes.Object_11.skeleton} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/legend.glb')
